trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: 'Install Rust'

- script: |
    sudo apt install -y cmake g++ pkg-config jq
    sudo apt install -y libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
    cargo install cargo-kcov
    cargo kcov --print-install-kcov-sh | sh
  displayName: 'Install cargo-kcov'

- script: |
    # source $HOME/.cargo/env
    cargo kcov -o .coverage/unit --bin rusty-hook -- --exclude-pattern=_test.rs,main.rs
    echo hello
    sudo chmod +rw .coverage -R
    ls .coverage/unit/kcov-merged
    cat .coverage/unit/kcov-merged/cobertura.xml
  displayName: 'Run tests'

# Publish Cobertura code coverage results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: .coverage/unit/kcov-merged/cobertura.xml
    #reportDirectory: # Optional
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional
  displayName: 'Publish coverage results'
