trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: 'Install Rust'

- task: DownloadPipelineArtifact@0
  displayName: 'Download kcov executable'
  inputs:
    pipelineId: 1359
    artifactName: 'kcov'
    targetPath: '~/.cargo/bin'

- script: |
    cargo install cargo-kcov
  displayName: 'Install cargo-kcov'

- script: |
    # source $HOME/.cargo/env
    cargo kcov --kcov ~/.cargo/bin/kcov  -o .coverage/unit --bin rusty-hook -- --exclude-pattern=_test.rs,main.rs
    echo hello
    sudo chmod +rw .coverage -R
    ls .coverage/unit/kcov-merged
    cat .coverage/unit/kcov-merged/cobertura.xml
  displayName: 'Run tests'

- task: cobertura-transform@0
  displayName: 'Transform Cobertura Format From 3 to 4'
  inputs:
    cobertura3FilePath: .coverage/unit/kcov-merged/cobertura.xml
    cobertura4FilePath: .coverage/unit/kcov-merged/cobertura4.xml


# Publish Cobertura code coverage results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/.coverage/unit/kcov-merged/cobertura4.xml'
    reportDirectory: '$(Build.SourcesDirectory)/.coverage/unit/kcov-merged'
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional
  displayName: 'Publish coverage results'
