[package]
name = "rusty-hook"
version = "0.1.2"
authors = ["Swellaby <opensource@swellaby.com>"]
description = "work in progress, git hook utility"
license = "MIT"
repository = "https://github.com/swellaby/rusty-hook"
readme = "README.md"
edition = "2018"
exclude = [
  ".coverage/**",
  ".testresults/**",
  ".vscode/**",
  ".github/**",
  ".editorconfig",
  ".gitattributes",
  ".rustfmt.toml",
  ".rusty-hook.toml",
  "azure-pipelines.yml",
  ".azure-pipelines/**",
  "kcov*/**",
  "**/*.gcda",
  "**/*.gcno",
]

[dependencies]
ci_info = "0.3.1"
getopts = "0.2.18"
toml = "0.4.10"
